### ISSUE TITLE
docker build -t epc-web:mybuild ./ not work

### ISSUE THREAD

**Issue by stolaf** [scusi/epc-web#3]
Sending build context to Docker daemon  526.8kB
Step 1/20 : FROM golang:1.18.0-stretch AS builder
 ---> 3c14e0626782
Step 2/20 : ENV GO111MODULE=on     CGO_ENABLED=1
 ---> Using cache
 ---> 30c208977547
Step 3/20 : WORKDIR /build
 ---> Using cache
 ---> e78f0cace505
Step 4/20 : COPY go.mod .
 ---> Using cache
 ---> 0e59bccfa36d
Step 5/20 : RUN go mod download
 ---> Using cache
 ---> 2d68e756aba2
Step 6/20 : COPY . .
 ---> Using cache
 ---> 480afaaea567
Step 7/20 : RUN go build ./
 ---> Running in e5cfc3087141
go: downloading github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e
go: updates to go.mod needed; to update it:
        go mod tidy
The command '/bin/sh -c go build ./' returned a non-zero code: 1

**Comment by scusi** [comment]
fixed with commit 4181ef6.

----

Hi Olaf,

ich freu mich dass du meinen code ausprobieren willst. Danke.
Ich hab das Problem hoffentlich mit commit 4181ef6 behoben.

Zu deiner Info, mit einem simplen `go mod tidy` hättest du es auch
selber beheben können, allerding snur bei dir.
So ist es jetzt auch für alle anderen Nutzer behoben.

Schick ruhig weiter bugs, wenn du welche findest.

Liebe Grüße aus der Eifel.

Florian 'scusi' Walther
